### ISSUE TITLE
Cannot "purge from" the oldest message in a channel

### ISSUE THREAD

**Issue by walkergray** [wakfi/roboboi#1]
Even if it would otherwise be a valid purge
`//purge from | <oldest message in channel ID>`
Returns error about the range being too large

**Comment by wakfi** [comment]
Unassigning until this is being worked on. Low

**Comment by wakfi** [comment]
Would raise the priority of this but it's too much of an edge case to occur frequently

**Comment by wakfi** [comment]
Marking this as wontfix for now but am open to the idea of revisiting at some point in the future
