### ISSUE TITLE
'-t' flag doesn't respond to the available aliases for each activity type in //setActivity command.

### ISSUE THREAD

**Issue by nocturnalsushi** [wakfi/roboboi#49]
## Short Description
While using the ```-t``` flag, you are unable to use aliases for each activity type such as 'listen' for 'LISTENING' or 'play' for 'PLAYING'.
## Steps to Reproduce

Step 1: Use the //setActivity command with the flag ```-t```

Step 2: Send the command and observe

## Expected Result (how *should* it be behaving?)
The bot must parse the alias of the activity type for the same.
## Actual Result (what is the *current* behavior?)
The bot responds with a confirmation message mentioning that the status was set/changed whereas it actually isn't.
## Current Bot Version (run the `info` command and look at the footer)
v2.0.0
## Attachment
Actual result:
https://i.gyazo.com/aa2944fad85da6c0636d1eca197eeb21.mp4

**Comment by wakfi** [comment]
Verified
